export interface Exam{
    id?: string,
    polyura:number,
    polydipsia:number,
    weigtht_loss:number,
    weakness:number,
    polyfagia:number,
    genital_thrush:number,
    visual_blurring:number,
    itchinf:number,
    irritabilty:number,
    delayed_healing:number,
    partial_paresis:number,
    muscle_stiffness:number,
    Alopecia:number,
    Obesity:number,
    results:string,
    coments:string,
    notification:string,
    date:string,
    age:number,
    gender:number,
}